version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    build:
      context: kafka-docker-master
      dockerfile: Dockerfile
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.40
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
#      KAFKA_CREATE_TOPICS: "mytopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mongo_db:
    image: mongo:4.2
    ports:
    - 27017:27017
  kafka_producer:
    build:
     context: kafka-producer
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  kafka_consumer_topic_one:
    build:
     context: kafka-consumer-topic-one
     dockerfile: Dockerfile
    ports:
     - "8081:8081"
    depends_on:
     - kafka_producer
     - mongo_db
  kafka_consumer_topic_two:
    build:
     context: kafka-consumer-topic-two
     dockerfile: Dockerfile
    ports:
     - "8082:8082"
    depends_on:
     - kafka_producer