server:
  port: 8081

kafka:
  bootstrapAddress: ${MY_IP}:9092
  topicOne: topicA
  groupId: group1

spring:
  data:
    mongodb:
      host: ${MY_IP}
      port: 27017
      database: my-db
      username: root
      password: root
      authentication-database: admin
