server:
  port: 8081

kafka:
  bootstrapAddress: 192.168.1.40:9092
  topicOne: topicA
  groupId: group1

spring:
  data:
    mongodb:
      host: 192.168.1.40
      port: 27017
      database: my-db
      username: root
      password: root
      authentication-database: admin
